/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/Owl_Animations.gltf");
  const { actions } = useAnimations(animations, group);
  useEffect(() => {
    actions.Fly.timeScale = 0.33
    actions.Fly.play();
  }, []);
  console.log(actions);
  return (
    <group ref={group} {...props} dispose={null}>
      <primitive object={nodes.root} />
      <skinnedMesh
        geometry={nodes.Owl.geometry}
        material={materials.Mat_Owl}
        skeleton={nodes.Owl.skeleton}
      />
    </group>
  );
}

useGLTF.preload("/Owl_Animations.gltf");
